%% REQUIRES OBJECTS SOS AND G TO BE GENERATED BY filterDesigner
file_name = 'cfg2.txt';
c_data_w = 16;
c_len_frac = 13;
m = size(SOS,1);
a = [5 6 2 3]; % re-ordering coeffs -> a2, a3, b2, b3
y = zeros(m, 8);
%% REORDER COEFFICIENTS
for i = 1:m
    for j = 1:5
        if j > 1
            y(i,j) = y(i,j) + SOS(i,a(j-1));
        else
            y(i,1) = G(i);
        end
    end 
end
%% PRINT TO FILE AS CONSTANT DECLARATION
% fID = fopen(file_name, 'wt');
% fprintf(fID, "constant c_coeff_mem_init : t_coeff_mem := (\n\t");
% for i = 1:m % m = rows of SOS -> number of sections
%     for j = 1:8 %8 is the closest higher exponent of 2 (section mem. width)
%         x = y(i,j);
%         x_sfi = sfi(x, c_data_w, c_len_frac);
%         if i==m && j==8
%             fprintf(fID, '"%s"', x_sfi.bin); %%no comma afte last coeff
%         else
%             fprintf(fID, '"%s",', x_sfi.bin);
%         end
%     end
%     if i==m
%         fprintf(fID, "\n);");
%     else
%         fprintf(fID, "\n\t");
%     end
% end
%% PRINT TO FILE FOR TEST BENCH READING
fID = fopen(file_name, 'wt');
for i = 1:m
    for j = 1:8
        x = y(i,j);
        x_sfi = sfi(x, c_data_w, c_len_frac);
        if i == m && j == 8
            fprintf(fID, '%s', x_sfi.bin);
        else
            fprintf(fID, '%s\n', x_sfi.bin);
        end
    end
end
fclose(fID);